server:
  tomcat:
    basedir: tempfile
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1000
  servlet:
    context-path: /
#登录超时时间(毫秒)：1小时
login.session.timeout.ms: 3600000
logging:
  config: classpath:logback-spring.xml
  level:
        com.homework.core.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjyz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #password: 123456
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
      connection-timeout: 5000
  aop:
    proxy-target-class: true
    auto: true
  http:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 20MB

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


